# config/packages/api_platform.yaml
api_platform:
    title: 'Symfony REST API'
    description: 'A Symfony API to manage a simple blog app.'
    version: '1.0.0'
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Entity' # default configuration for annotations
            - '%kernel.project_dir%/config/api_platform' # yaml or xml directory configuration
    formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        html:     ['text/html']
        jsonhal:  ['application/hal+json']
    patch_formats:
        json:     ['application/json']
        jsonld:   ['application/ld+json']
        jsonhal:  ['application/hal+json']
        jsonapi:  ['application/vnd.api+json']
    error_formats:
        json:                          ['application/json']
        jsonld:                        ['application/ld+json']      # Hydra error formats
        jsonproblem:                   ['application/problem+json']
        jsonapi:                       ['application/vnd.api+json']
    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: Authorization
                type: header
    oauth:

        # The oauth token url.
        tokenUrl: '/oauth/v2/token'

        # The oauth authentication url.
        authorizationUrl: '/oauth/v2/auth'
