#index:
#    path: /
#    controller: App\Controller\DefaultController::index

login_check:
    path:     /login_check
    methods:  [POST]

api_login_check:
    path: /api/login_check

swagger_ui:
    path: /docs
    controller: api_platform.swagger.action.ui
level_post_publication:
    path: /api/level
    methods: ['POST']
    defaults:
        _controller: App\Controller\Config\LevelController::createLevel
        _api_resource_class: App\Entity\Config\Level
        _api_item_operation_name: post_publication
